import Arweave from "arweave";
import {ChainClientParams, Network} from "@d11k-ts/client";
import {validatePhrase} from "@d11k-ts/crypto";
import {getKeyFromMnemonic} from "arweave-mnemonic-keys";
import Transaction from "arweave/node/lib/transaction";
import {ArTxDataResult, ArTxParams, ArTxs, ArTxsHistoryParams, GasfeeResult, TxStatusResponse} from "./types";
import ArweaveTxClient from "./tx-client";
import {ApiConfig} from "arweave/node/lib/api";
import {defaultArConfig} from "./utils";

export interface ArweaveChainClient {
    getAddress(): Promise<string>,
    mintArTokens(pubAddress: string): Promise<void>
    getBalance(address: string): Promise<number>,
    getFees(rawTx: Transaction): GasfeeResult
    transfer({recipient, amount}: ArTxParams): Promise<string>,
    getTransactionData(txHash: string): Promise<ArTxDataResult>,
    getTransactionsHistory(params: ArTxsHistoryParams): Promise<ArTxs>
    getTxStatus(txHash: string): Promise<TxStatusResponse>
}

export type ChainConfigParams = {
    config?: ApiConfig
}

class ArweaveClient extends ArweaveTxClient implements ArweaveChainClient {
    protected network: Network;
    protected arweave: Arweave;
    protected phrase = '';
    constructor({
                    phrase,
                    network = Network.Mainnet,
                    config = defaultArConfig
                }: ChainClientParams & ChainConfigParams) {
        super()
        if (phrase) {
            if (!validatePhrase(phrase)) {
                throw new Error('Invalid phrase')
            }
            this.phrase = phrase
        }
        this.network = network
        if ((this.network !== Network.Mainnet) && config === defaultArConfig) {
            throw Error(`'config' params can't be empty for 'testnet' or 'stagenet'`)
        }
        this.arweave = Arweave.init(config)
    }

    async getAddress(): Promise<string> {
        const keyPair = await getKeyFromMnemonic(this.phrase);
        const address = await this.arweave.wallets.jwkToAddress(keyPair);
        return address;
    }

    /** testnet tokens in winston */
    async mintArTokens(address: string) {
        const test_ar_amount = 5000000000000;

        // Mint balance in Arlocal for testing
        await this.arweave.api.get(`/mint/${address}/${test_ar_amount}`);
        await this.arweave.api.get("/mine");
    }

    async getBalance(address: string): Promise<number> {
        /** Get balance */
        let wnstBalance = await this.arweave.wallets.getBalance(address);

        /** Convert balance from Winston to Ar. (1 Ar = 10^12) */
        const arBalance = this.arweave.ar.winstonToAr(wnstBalance);

        return Number(arBalance);
    }

    /** Calculate gasFee required for transaction */
    getFees(rawTx: Transaction): GasfeeResult {
        /**  Gas fee generated by default during 'createTransaction' */
        const arw_gasFee = Number(rawTx.reward);
        return {
            slow: arw_gasFee,
            average: arw_gasFee,
            fast: arw_gasFee,
        }
    }

    /** Create transaction based on user inputs */
    async createTransaction(
        recipient: string,
        amount: number
    ): Promise<Transaction> {
        const pvtKey = await getKeyFromMnemonic(this.phrase);
        // const pubAddress = await this.arweave.wallets.jwkToAddress(pvtKey);

        // Create transaction
        const rawTx = await this.arweave.createTransaction(
            {
                target: recipient, // Receiver address
                quantity: this.arweave.ar.arToWinston(amount.toString()), // Amount to transfer in Ar
            },
            pvtKey
        );

        return rawTx;
    }

    /** Sign and Send the transaction */
    async signAndSend(rawTx: Transaction): Promise<string> {
        const pvtKey = await getKeyFromMnemonic(this.phrase);
        // const pubAddress = await this._arweave.wallets.jwkToAddress(pvtKey);

        /** Sign transaction and retreive status */
        await this.arweave.transactions.sign(rawTx, pvtKey);
        const status = await this.arweave.transactions.post(rawTx);
        await this.arweave.api.get("/mine");

        if (status.status !== 200) throw Error(`Transaction error or invalid`)

        return rawTx.id;
    }

    async transfer({recipient, amount}: ArTxParams): Promise<string> {
        const rawTx = await this.createTransaction(recipient, amount)

        const txHash = await this.signAndSend(rawTx)

        return txHash
    }

    /**  Get status data using transaction hash / id */
    async getTxStatus(txHash: string): Promise<TxStatusResponse> {
        const statusData = await this.arweave.transactions.getStatus(txHash);
        return statusData
    }

    async getTransactionData(txHash: string): Promise<ArTxDataResult> {
        const txData = await this.getTxData(this.arweave, txHash)
        return txData
    }

    async getTransactionsHistory(params: ArTxsHistoryParams): Promise<ArTxs> {
        const txs = await this.getTxsHistory(this.arweave, params.address, params.limit ? params.limit : 100)
        const txsResult = {
            total: txs.inner.length,
            txs
        }
        return txsResult
    }
}

export { ArweaveClient }